{
    The Enchanted Keyfinder is a free utility that retrieves your
    Product Key (cd key) used to install Windows from your registry.

    Copyright (C) 2011 Enchanted Keyfinder Project

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    The initial developer of this code is VersionBoy.
    Portions created by VersionBoy are Copyright (C) 2011.
    All Rights Reserved.

    Contributor(s):
                    Oliver Schneider (assarbad)
                    Sam Gleske (sag47)
                    VersionBoy (versionboy)

    Compiles With: Delphi 7, Boreland Dev Studio 2006, DS Turbo Delphi 2006, Delphi 2007
}
const
  PROGRAM_NAME = 'Enchanted Keyfinder';
  kfVersion = '0.1 Beta 6';
  kfStableVersion = '0.0.0';
  kfUnstableVersion = '0.1 Beta 6';
  PROGRAM_RELEASE_DATE = 'February 17th, 2011';
  PROGRAM_HOME_PAGE = 'http://ekeyfinder.sourceforge.net/';
  PROGRAM_SOURCEFORGE_HOME_PAGE = 'http://sourceforge.net/projects/ekeyfinder/';
  PROGRAM_SOURCEFORGE_PHPBB_PAGE = 'http://sourceforge.net/apps/phpbb/ekeyfinder/';
  PROGRAM_SOURCEFORGE_WIKI_PAGE = 'http://sourceforge.net/apps/mediawiki/ekeyfinder/';
  PROGRAM_FEATURE_TRACKER = 'http://sourceforge.net/tracker/?group_id=369948';
  PROGRAM_SVN_TRUNK = 'http://ekeyfinder.svn.sourceforge.net/svnroot/ekeyfinder/trunk/keyfinder/';
  UPDATE_URL = 'http://ekeyfinder.sourceforge.net/update.ini';
